### ISSUE TITLE
Work together with kala?

### ISSUE THREAD

**Issue by falschparker82** [victorcoder/dcron#7]
Man, how I wish Kala and Dcron would just work together.

https://github.com/ajvb/kala

https://github.com/victorcoder/dcron

Fusing both would be AWESOME (I'd even like to help).

What Dcron gets right:

- Distributed by design

- Raft for the reliable parts, gossip for lightweight sync, a match made in heaven

- Linux mentality

- Dashboard included

- Good docs, nice website, looks serious

What Kala gets right:

- Built much more directly after Chronos, which has an amazing and battle tested API

- Using ISO durations instead of NIHing their own format

- Dependent jobs

**Comment by victorcoder** [comment]
@falschparker82 This project is still open to improve a lot. 

Dcron also borrowed a lot of concepts from Chronos, the API actually so you can discard the first difference with Kala.

Using ISO durations is not difficult to implement, but IMO the used [cron lib](https://godoc.org/github.com/robfig/cron) is very clear and easy to understand, I need to think more on this topic though.

Dependent jobs: This is a very good point, IMO this is very difficult to implement it right and I don't want to approach this right now. I want the project to more mature before implementing it, but it's on top of the list.

Said that, I open to collaborate with other projects that has similar goals, but AFAIK Kala it's very different by design.
